# Generated by Django 5.0.6 on 2024-06-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_comments_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, default='assiette_vide.jpg', upload_to=''),
        ),
    ]
