# Generated by Django 5.0.6 on 2024-06-11 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_recipes_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='likes',
            field=models.ManyToManyField(related_name='likedrecipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
