# Generated by Django 5.0.6 on 2024-06-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_likedrecipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Likedrecipes',
        ),
    ]
