# Generated by Django 5.0.6 on 2024-07-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_recipes_likes_delete_likedrecipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.CharField(max_length=250),
        ),
    ]
